name: Print Secrets

on: [workflow_dispatch]

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print JWT_SECRET_KEY
        run: echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}"
      - name: Print SECRET_KEY
        run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"
      - name: Print SENDGRID_API_KEY
        run: echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}"
